// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import { defineConfig } from 'prisma/config';
import { Pool } from '@neondatabase/serverless';
import { PrismaNeon } from '@prisma/adapter-neon';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasources: {
    db: {
      provider: 'postgresql',
      connectionString: process.env.DATABASE_URL,
    },
  },
});
